### ISSUE TITLE
新的 commit 使名字竞技场版本回滚

### ISSUE THREAD

**Issue by sqrt2802** [rinick/rinick.github.io#1]
这个 repo 内有 master 和 gh-pages 两个长期共存的分支。名字竞技场网页 `deepmess.com/namerena/` 指向 master 分支中的文件，玩家社区也一直使用 master 分支下的名竞进行游玩。提交记录可以看出，近几年的名竞更新都在 master 上提交，包括 2021 年的最近一次更新。
几天前我们发现，`deepmess.com/namerena` 的战斗结果发生了变化。经过验证，这一网址不再指向原来的 master 分支，而是改变为指向 gh-pages。我们猜测这是因为 gh-pages 上 hashdown 的更新使 GitHub Pages 配置发生变化，导致名字竞技场意外回滚到了 gh-pages 分支上的旧版本。
如果这一更改确实是您无意间做出的，我们请求您将名字竞技场恢复至 master 分支下的版本，这可以防止玩家们产生误会，同时也更有利于新人游玩。
谢谢。

**Comment by rinick** [comment]
好了，改回去了
